### ISSUE TITLE
Some Error When Run

### ISSUE THREAD

**Issue by sml002** [avatarsdk/metaperson-ue-sample#1]
![image](https://github.com/avatarsdk/metaperson-ue-sample/assets/144324486/ecd84a34-93d6-4ff9-8f21-1aee723ced01)
Default Property warnings and errors.Error: cDO Constructor (Metaperson2GameMode): Failed to findGame/ThirdPerson/Blueprints/Bp ThirdPersonCharacter.Bp ThirdPersonCharacterC
Error: cDO Constructor (Metaperson2GameMode): Failed to findGame/ThirdPerson/Blueprints/BP HUD.BP HUD C

**Comment by nsdfxela** [comment]
Could you please pull the latest changes and try to run the project again?

**Comment by sml002** [comment]
Thank you !  

The previous problem has been resolved.
But a new error has emerged. 

![image](https://github.com/avatarsdk/metaperson-ue-sample/assets/144324486/264432b9-3f5a-4f6f-a0da-93d0bba2f418)

**Comment by nsdfxela** [comment]
Fixed the issue. Please try to pull latest update and run the project.

**Comment by nsdfxela** [comment]
@sml002 could you please check on your side?
